### ISSUE TITLE
Refreshing/accessing page with Dynamic Route blocks rendering?

### ISSUE THREAD

**Issue by MaximeHeckel** [netlify/next-on-netlify#132] opened 2021-01-07 03:01 UTC
**Describe the bug**
Hi all 👋 first of all thank you for this project, I've been following it for a while and I'm really happy about Netlify's commitment to NextJS

My issue is a bit of a weird one: I deployed my Next.JS v10 blog on Netlify using next-on-netlify, the build is successful, all my
posts are being rendered (SSG) properly. My Next.JS blog is fairly basic in terms of setup: I have a landing page under `pages/index.tsx` and dynamic route `pages/posts/[slug].tsx` that relies on getStaticProps and getStaticPaths (you can see this file here => [[slug].tsx](https://github.com/MaximeHeckel/blog.maximeheckel.com/blob/next/pages/posts/%5Bslug%5D.tsx) it's fairly short)

I can access the landing page (using next/link), refresh the landing page, and navigate to a blog post without any problem.

However, refreshing one of my blog posts, or accessing directly a link of a blog post breaks the page: it gets "stuck"  does not fully "render" I'd say as if the rendering was stuck (??)

Maybe a video can describe it better (left is Vercel, right is Netlify with next-on-netlify):

https://user-images.githubusercontent.com/2974412/103845202-90705080-5069-11eb-9001-8134a68cc1c0.mp4 

I tried to deploy my blog on Vercel and it worked without any trouble: https://testblog.maximeheckel.vercel.app/posts/guide-animations-spark-joy-framer-motion/ (loading this will load and behave as expected, you can click on buttons, scroll the page and see element properly rendered) 

Here's the netlify hosted version built with next-on-netlify: https://5ff671771e2cb8000841be6e--blogmaximeheckel.netlify.app/posts/guide-animations-spark-joy-framer-motion/

Here are the build logs (I made them public, let me know if you can access them): https://app.netlify.com/sites/blogmaximeheckel/deploys/5ff6748f5011f2000739c2b4

I tried to simplify my blog as much as possible trying to find the root cause, but I could go as deep as I wanted, it was impossible to get proper behavior, the bug would persist whether my page had content or not thus I feel it's linked to the fact this is a page with dynamic route. I will try to come up with a minimum reproduction but in the meantime feel free to use my blog's Next.JS branch: https://github.com/MaximeHeckel/blog.maximeheckel.com/tree/next

Also note that this ONLY happens in the case when I deploy/build on Netlify with next-on-netlify. I tried on Vercel, I tried building locally, even with netlify-dev CLI, everything works as expected

I'm not really sure what's happening here but felt like this was likely related to this project as the Vercel deployment works as expected (of course let me know if that isn't the case 😄 )

**To Reproduce**
Steps to reproduce:
1. Go to deploy the project above on Netlify https://github.com/MaximeHeckel/blog.maximeheckel.com/tree/next
2. Access the preview/deployment
3. Access one of the post / dynamic route 
4. See the post rendering properly
5. Refresh the page
6. See the error, the page is like stuck

**Versions**
 - Next: `10.0.4`
 - next-on-netlify: `2.7.0`
 
 UPDATE 1:
 
 Maybe it's nothing but I've noticed the following thing happening in the netlify/next-on-netlify version of the site, but there are quite a few:
 
 ```
 The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
 ```
 
 
 9 warnings when accessing the page through the landing page (next/link)
<img width="1448" alt="Screen Shot 2021-01-06 at 11 51 44 PM" src="https://user-images.githubusercontent.com/2974412/103852714-725f1c00-507a-11eb-9576-f9ac69512baf.png">

15 warnings when accessing the page directly or refreshing the post page
<img width="1448" alt="Screen Shot 2021-01-06 at 11 52 08 PM" src="https://user-images.githubusercontent.com/2974412/103852792-a4707e00-507a-11eb-8dc7-ad0654ca980a.png">

**Comment by MaximeHeckel** [comment] 2021-01-07 05:25
Ok I think I figured it out!
Basically, disabling any kind of "Post Processing" in the "Deploy Settings" on Netlify UI fixes this issue, took me a few hours to find this one 😅

Do you know what's the underlying reason behind that?  Maybe this could be a contribution to the docs?

**Comment by lindsaylevine** [comment] 2021-01-09 11:16
hey @MaximeHeckel! thanks so much for opening such a detailed issue and for your kind words! we caught wind of your tweet and i've been trying to track down some more info about post processing internally 😆 

![Screen Shot 2021-01-09 at 6 14 13 AM](https://user-images.githubusercontent.com/57350178/104090054-eef02700-5241-11eb-8826-cec62273675d.png)

appreciate the update and sorry this took you a few hours to diagnose!!! sounds like it must've been a pain to find 😅 .

i agree at the very least we should update our docs/README to reflect that post processing with next.js may cause this type of issue (and possibly others).

will also try to get some more insight on why this is an issue and update you here. many thanks again!

**Comment by MaximeHeckel** [comment] 2021-01-09 15:29
@lindsaylevine thank you for your reply! 

And no worries, I'm really excited about advanced NextJS support on Netlify! For the moment this project is just me experimenting thus I'm not in a rush at all

I will keep an eye out for updates regarding this, would love to know why this happened 😄

**Comment by lindsaylevine** [comment] 2021-01-15 11:16
hey @MaximeHeckel! i believe i have some sort of update. it seems the js bundled by netlify and hosted on cloudfront is missing a snippet. see line 16:

<img width="949" alt="Screen Shot 2021-01-15 at 5 00 42 AM" src="https://user-images.githubusercontent.com/57350178/104718207-86e58900-56f8-11eb-8598-b0eb711c248d.png">

i assume this is because the file name has brackets in it, an issue we've seen in other parts of netlify. i haven't confirmed that it's _this_ missing snippet that is causing your issue, but it's the only lead/hunch right now. i've pinged people in slack to make sure our bundling can handle file names with brackets.

all that said, i think we'll recommend _not_ using post processing bundling for next projects on netlify, since next already bundles everything. with that, i'll close the issue, BUT, if i discover anything new, i'll still circle back here :). i also think i'll slightly rename this issue so anyone looking through our closed issues for something similar can find it! <3

**Closed by lindsaylevine** 2021-01-15 11:16 UTC
Labels: priority: low
