### ISSUE TITLE
Ability to specify custom directories for static and function output. 

### ISSUE THREAD

**Issue by mashaalmemon** [netlify/next-on-netlify#109] opened 2020-12-08 17:21 UTC
**Is your feature request related to a problem? Please describe.**

Would love to be able to set the function output and publish path to something I choose vs 'out_functions' and 'out_publish'

**Describe the solution you'd like**

Would like to be able to specify the publish/function output directory so I can structure my project directory that way I'd like to.

**Describe alternatives you've considered**

Only option is to stick to the pattern you've provided. Or not use next-on-netlify.

**Additional context**

None. Curious on when this might be implemented? Is it on the roadmap?

**Comment by lindsaylevine** [comment] 2020-12-10 04:39
hey! you can (and should!) use https://github.com/netlify/netlify-plugin-nextjs - this will respect the functions and publish dirs you define in your toml file. it is the next iteration of next-on-netlify, in beta; it simply extends next-on-netlify without the extra configuration steps and with this additional customization. in the near future, all apps using next-on-netlify manually will be encouraged to switch to the plugin, with the option to continue using NoN manually if that's their preference. that said, this feature will likely not be incorporated into classic next-on-netlify.

this is also somewhat a duplicate of https://github.com/netlify/next-on-netlify/issues/36 so i'm going to close the issue for now. feel free to re-comment or open again if you think that's needed!

**Closed by lindsaylevine** 2020-12-10 04:39 UTC
Labels: duplicate
